// Names and durations are derived from the application and installed Auth SDK.
export const STORAGE_INVENTORY=[
 {name:"embedbot_cookie_consent",provider:"EmbedBot",purpose:"Gemmer accepteret/afvist analyse, version og valgt tidspunkt",type:"localStorage (nødvendig præference)",expiry:"Ingen automatisk udløbstid. Nyt samtykke kræves ved ny consent-version; kan slettes i browseren."},
 {name:"sb-<projektreference>-auth-token (eventuelt .0, .1 …)",provider:"Supabase Auth",purpose:"Login-session; kan opdeles i cookie-chunks",type:"Cookie (nødvendig)",expiry:"SDK-standard i installeret @supabase/ssr: 400 dage. Token/session kan udløbe tidligere; produktionsindstillinger skal kontrolleres."},
 {name:"sb-<projektreference>-auth-token-code-verifier (eventuelt chunks)",provider:"Supabase Auth",purpose:"PKCE-verifikation ved login/password reset",type:"Cookie (nødvendig)",expiry:"Ryddes når auth-flowet udveksler koden; SDK-standard for cookie maxAge er 400 dage. Verificér det konkrete auth-flow i drift."},
 {name:"onboarding_business_id",provider:"EmbedBot",purpose:"Reference til igangværende chatbotopsætning",type:"localStorage (nødvendig)",expiry:"Ryddes af setup-flowet; ingen automatisk TTL i eksisterende implementation."},
 {name:"onboarding_form_snapshot",provider:"EmbedBot",purpose:"Bevarer igangværende virksomhedsskabelon mellem opsætningstrin",type:"localStorage (nødvendig)",expiry:"Ryddes ved gennemført gratis prøve; igangværende kladde har ingen automatisk TTL."},
 {name:"dashboard_fresh_login_at",provider:"EmbedBot",purpose:"Teknisk markering af seneste login i fanen",type:"sessionStorage (nødvendig)",expiry:"Når fanens browsersession afsluttes."},
 {name:"commerce_oauth",provider:"EmbedBot",purpose:"Krypteret tilstand til Shopify-forbindelsens callback",type:"HttpOnly cookie (nødvendig)",expiry:"600 sekunder (10 minutter); slettes også ved callback."},
 {name:"Ingen app-oprettede analyse-cookies/storage",provider:"Plausible / Vercel",purpose:"Samtykkebaseret analyse og hastighedsmåling",type:"Netværksmålinger efter accept",expiry:"Browseren gemmer ikke en app-defineret identifikator til disse målinger. Leverandørernes serverretention kræver verificering."},
 {name:"Ingen persistent lagring i widgetten",provider:"EmbedBot",purpose:"Konfiguration, sessionnonce, chat og references bevares kun i memory",type:"Memory i siden",expiry:"Forsvinder når siden lukkes/genindlæses. Historiske embedbot-config-<id>-nøgler anvendes ikke længere og kan slettes via browserindstillinger."},
];
