export type Supplier = { provider:string; legalName:string; service:string; purpose:string; data:string; location:string; role:string; transfer:string; addedAt:string; information:string; evidence:string };
const unknown="Requires verification";
// Provider names are evidenced by imports/configuration. They do not establish a legal contracting entity or transfer basis.
export const SUPPLIERS: Supplier[] = [
 {provider:"Supabase",service:"Database og Auth",purpose:"Konto, chat, supportsager, videnskilder og integrationer",data:"Konto-/virksomhedsoplysninger, chat og supportsager; krypterede webshopcredentials",location:"Projektets database-region: eu-central-1 (verificeret 2026-10-02). Auth, logs, backups og supportadgang: Requires verification",information:"https://supabase.com/privacy",evidence:"@supabase/ssr, @supabase/supabase-js; projektmetadata",legalName:unknown,role:unknown,transfer:unknown,addedAt:unknown},
 {provider:"OpenAI",service:"AI API",purpose:"Chatgenerering og embeddings af videnskilder",data:"Spørgsmål, begrænset historik og udvalgte virksomhedskilder. Private ordreopslag håndteres separat",information:"https://openai.com/policies/data-processing-addendum/",evidence:"lib/chatbot.ts og chat-/ingest-routes",legalName:unknown,location:unknown,role:unknown,transfer:unknown,addedAt:unknown},
 {provider:"Vercel",service:"Hosting, Cron, Web Analytics og Speed Insights",purpose:"Levering, jobs og samtykkebaseret måling",data:"HTTP-trafik, serverbehandling og samtykkebaserede besøgs-/ydelsesdata",information:"https://vercel.com/legal/dpa",evidence:"vercel.json, Next.js og analytics-komponenten",legalName:unknown,location:unknown,role:unknown,transfer:unknown,addedAt:unknown},
 {provider:"Resend",service:"Transaktionsmail",purpose:"Aktivering, support og sagsnotifikation",data:"Emailadresse og relevant emailindhold, herunder ticketoplysninger",information:"https://resend.com/legal/dpa",evidence:"lib/business-activation.ts, lib/commerce/mail.ts",legalName:unknown,location:unknown,role:unknown,transfer:unknown,addedAt:unknown},
 {provider:"Stripe",service:"Betalte abonnementer",purpose:"Betaling, abonnement og opsigelse",data:"Kunde-/virksomhedsreference, email og betalingsoplysninger hos Stripe",information:"https://stripe.com/legal/dpa",evidence:"stripe-webhook, billing routes og checkout-links",legalName:unknown,location:unknown,role:unknown,transfer:unknown,addedAt:unknown},
 {provider:"Plausible",service:"Webanalyse",purpose:"Samtykkebaseret besøgsmåling",data:"Sidebesøg og tekniske besøgsoplysninger",information:"https://plausible.io/data-policy",evidence:"app/components/cookie-consent.tsx",legalName:unknown,location:unknown,role:unknown,transfer:unknown,addedAt:unknown},
];
