"use client";
import { useEffect, useState, type FormEvent } from "react";
import Script from "next/script";
export default function WidgetPage(){
 const [path,setPath]=useState("/"),[quote,setQuote]=useState(false),[ready,setReady]=useState(false),[cacheKey,setCacheKey]=useState(0),[review,setReview]=useState(false),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const [email,setEmail]=useState(""),[need,setNeed]=useState(""),[budget,setBudget]=useState(""),[timing,setTiming]=useState("");
 useEffect(()=>{const params=new URLSearchParams(window.location.search);setPath(params.get("path")||"/");setQuote(params.get("quote")==="1");setCacheKey(Date.now());setReady(true);},[]);
 async function send(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/local-workspace",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"lead_create",email,need,budget,timing,page:path})});const d=await r.json();if(!r.ok)throw new Error(d.error);setSent(true);}catch(e){setError(e instanceof Error?e.message:"Henvendelsen kunne ikke gemmes.");}finally{setBusy(false);}}
 const field={display:"flex",flexDirection:"column" as const,gap:5,fontSize:12};const input={border:"1px solid var(--border-strong)",borderRadius:7,padding:9,width:"100%",font:"inherit",background:"var(--bg-primary)"};const button={border:0,borderRadius:7,padding:"11px 15px",background:"var(--accent)",color:"white",cursor:"pointer",font:"inherit"};
 return <main id="main-content" style={{minHeight:"100vh",padding:24,background:"var(--bg-secondary)",fontFamily:"var(--font-inter),sans-serif",color:"var(--text-primary)"}}><div style={{fontSize:11,color:"var(--text-muted)",letterSpacing:1}}>NORDIC LIVING · LOKAL TESTSIDE</div><h1 style={{fontSize:24,fontWeight:500,marginTop:16}}>{path.startsWith("/produkter")?"Find noget til dit hjem":path==="/kontakt"?"Hvordan kan vi hjælpe?":"Velkommen indenfor"}</h1><p style={{fontSize:13,color:"var(--text-muted)",lineHeight:1.7}}>Side: {path}<br/>Prøv chatten nederst til højre. Startbeskederne følger dine indstillinger.</p><button style={{...button,marginBottom:20}} onClick={()=>setQuote(!quote)}>{quote?"Skjul tilbudsformular":"Få et tilbud"}</button>
 {quote?<section style={{background:"var(--bg-primary)",padding:20,borderRadius:12,border:"1px solid var(--border)",maxWidth:500}}>{sent?<><h2 style={{fontSize:18}}>Din henvendelse er gemt lokalt</h2><p style={{fontSize:13,lineHeight:1.7}}>Den er oprettet som lead og supportsag i demoens dashboard. Ingen mail er sendt.</p><button style={button} onClick={()=>{setSent(false);setReview(false);setEmail("");setNeed("");setBudget("");setTiming("");}}>Prøv igen</button></>:review?<form onSubmit={send}><h2 style={{fontSize:18}}>Gennemgå din henvendelse</h2><p style={{fontSize:13,lineHeight:1.8,whiteSpace:"pre-wrap"}}>{need}<br/>Mail: {email}<br/>Budget: {budget||"Ikke oplyst"}<br/>Tidspunkt: {timing||"Ikke oplyst"}</p><div style={{display:"flex",gap:10}}><button style={button} disabled={busy}>Gem henvendelsen lokalt</button><button type="button" onClick={()=>setReview(false)} style={{...button,background:"var(--bg-secondary)",color:"var(--text-primary)"}}>Ret oplysninger</button></div></form>:<form onSubmit={e=>{e.preventDefault();setReview(true);}} style={{display:"flex",flexDirection:"column",gap:13}}><h2 style={{fontSize:18,margin:0}}>Fortæl os om dit behov</h2><label style={field}>Hvad ønsker du hjælp til?<textarea style={input} required maxLength={2000} value={need} onChange={e=>setNeed(e.target.value)}/></label><label style={field}>Din mail<input style={input} type="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/></label><label style={field}>Budget · valgfrit<input style={input} maxLength={100} value={budget} onChange={e=>setBudget(e.target.value)}/></label><label style={field}>Hvornår skal det være? · valgfrit<input style={input} maxLength={100} value={timing} onChange={e=>setTiming(e.target.value)}/></label><button style={button}>Gennemgå henvendelsen</button><small style={{fontSize:10,color:"var(--text-muted)"}}>Lokal demo. Brug eksempeloplysninger. Ingen mail bliver sendt.</small></form>}{error?<p role="alert" style={{color:"var(--danger)"}}>{error}</p>:null}</section>:<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:15,maxWidth:500,marginTop:26}}>{["Lampen Nord","Spisebordet Eg"].map((product,i)=><div key={product} style={{background:i?"var(--border)":"var(--bg-primary)",padding:"50px 15px 20px",borderRadius:10}}><span style={{fontSize:35}}>{i?"▰":"◒"}</span><h2 style={{fontSize:13,fontWeight:500}}>{product}</h2><p style={{fontSize:11,color:"var(--text-muted)"}}>En demo til at prøve din chatbot</p></div>)}</div>}
 {ready?<Script src={`/widget.js?id=local-workspace&v=${cacheKey}`} strategy="afterInteractive" data-local-path={path} data-local-open="true"/>:null}
 </main>;
}
