import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import UniversalBackButton from "./components/universal-back-button";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${poppins.variable} antialiased`}
      >
        <UniversalBackButton />
        {children}
      </body>
    </html>
  );
}
