import Link from "next/link";

export default function TermsOfService() {
  return (
    <main id="main-content" className="min-h-screen bg-white px-4 py-12 text-gray-900 sm:px-6 lg:px-8">
      <article className="privacy-policy mx-auto max-w-4xl">
        <div className="mb-10 not-prose">
          <Link href="/" className="text-sm font-medium text-gray-600 hover:text-gray-900">← Tilbage til EmbedBot</Link>
          <h1 className="mt-8 text-4xl font-bold tracking-tight text-gray-900">Vilkår for EmbedBot</h1>
          <p className="mt-3 text-base text-gray-600">Senest opdateret: <time dateTime="2026-09-17">17. september 2026</time></p>
        </div>
        <div className="not-prose my-8 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-amber-950">
          <p className="font-semibold">Kun for erhverv</p>
          <p className="mt-2 text-sm leading-6">EmbedBot udbydes til virksomheder og personer, der handler som led i deres erhverv. Du skal være mindst 18 år og have ret til at indgå aftalen på virksomhedens vegne.</p>
        </div>
        <section><h2>1. Aftalen</h2><p>Disse vilkår gælder for virksomhedens brug af EmbedBot, herunder dashboard, chatbot-widget, support, pilot og betalte abonnementer. Aftalen indgås med EmbedBot / Axel Bødker Frederiksen, Smallegade 42, 4. tv., e-mail <a href="mailto:axel@embedbot.dk">axel@embedbot.dk</a>, telefon <a href="tel:+4591551250">+45 91 55 12 50</a>.</p></section>
        <section><h2>2. Tjenesten</h2><p>EmbedBot leverer en AI-baseret chatbot, som kan bruge virksomhedens egne oplysninger og websiteindhold til at besvare besøgendes spørgsmål. Funktioner, kapacitet og inkluderede AI-svar afhænger af den valgte plan. Vi kan foretage rimelige produktændringer, når tjenestens væsentlige funktion ikke forringes væsentligt.</p></section>
        <section><h2>3. Pilot</h2><p>En angivet gratis pilot kræver ikke betalingskort og bliver ikke automatisk til et betalt abonnement. Efter pilotperioden vælger virksomheden selv, om den vil købe en plan. En privat demo eller pilot må ikke offentliggøres uden aftale.</p></section>
        <section><h2>4. Pris, betaling og fornyelse</h2><p>Aktuelle priser og plangrænser fremgår af <Link href="/prices">prissiden</Link>. Priser er i danske kroner pr. måned og eksklusive moms, medmindre andet er angivet. Betaling håndteres af Stripe.</p><p>Et betalt abonnement fornyes automatisk månedligt, indtil det opsiges. Den valgte pris, betalingsperiode og fornyelse vises før betaling. Virksomheden kan opsige i dashboardet; opsigelsen gælder ved udgangen af den allerede betalte periode. Se <Link href="/refunds">betalings- og refusionspolitikken</Link>.</p></section>
        <section><h2>5. Konto og adgang</h2><p>Virksomheden skal give korrekte oplysninger, beskytte loginoplysninger og straks kontakte os ved mistanke om misbrug. Virksomheden er ansvarlig for handlinger foretaget fra dens konto, medmindre de skyldes forhold, som EmbedBot er ansvarlig for.</p></section>
        <section><h2>6. Virksomhedens indhold og instruktioner</h2><p>Virksomheden beholder sine rettigheder til indhold, som den leverer. Virksomheden giver EmbedBot en begrænset ret til at behandle indholdet for at levere, sikre og supportere tjenesten.</p><p>Virksomheden er ansvarlig for, at den har ret til at bruge og dele indholdet, og for at produkt-, pris-, leverings-, retur-, garanti- og kontaktoplysninger er korrekte. Virksomheden skal gennemgå væsentlige chatbot-svar og må ikke instruere chatbotten i at vildlede kunder eller overtræde lovgivning.</p></section>
        <section><h2>7. Personoplysninger</h2><p>Når EmbedBot behandler virksomhedens besøgendes oplysninger efter virksomhedens instruktioner, er virksomheden normalt dataansvarlig og EmbedBot databehandler. Virksomheden skal give de nødvendige oplysninger til sine besøgende, vælge et lovligt behandlingsgrundlag og undgå at indsamle flere oplysninger end nødvendigt. En databehandleraftale kan indgås efter behov. Se <Link href="/privacy">privatlivspolitikken</Link> og <Link href="/cookies">cookiepolitikken</Link>.</p></section>
        <section><h2>8. Børn og følsomme oplysninger</h2><p>Tjenesten er ikke målrettet børn. Virksomheden må ikke målrette chatbotten mod børn eller indsamle børns oplysninger på grundlag af samtykke uden selv at sikre et gyldigt alders- og forældresamtykkeforløb. Chatbotten bør ikke bruges til CPR-numre, helbredsoplysninger, betalingskortoplysninger eller andre følsomme oplysninger, medmindre det er særskilt aftalt og lovligt.</p></section>
        <section><h2>9. Acceptabel brug</h2><p>EmbedBot må ikke bruges til ulovligt indhold, spam, phishing, chikane, malware, krænkelse af tredjemands rettigheder, omgåelse af sikkerhed eller belastning af tjenesten ud over normal brug. Sikkerhedsforanstaltninger må ikke testes uden skriftlig tilladelse.</p></section>
        <section><h2>10. AI-begrænsninger</h2><p>AI-genererede svar kan være ufuldstændige eller forkerte. EmbedBot bruger tekniske og instruktionelle sikkerhedsforanstaltninger, men kan ikke garantere, at alle fejl, manipulationer eller prompt-injection-forsøg bliver opdaget. Chatbotten må ikke være eneste grundlag for juridisk, medicinsk, finansiel eller anden højrisikorådgivning.</p></section>
        <section><h2>11. Tredjeparter</h2><p>Tjenesten anvender blandt andet OpenAI, Supabase, Stripe, Resend, Vercel og Plausible. Driftsforstyrrelser eller ændringer hos disse leverandører kan påvirke tjenesten. Vi vælger og administrerer leverandører med rimelig omhu, men kan ikke kontrollere deres tjenester fuldt ud.</p></section>
        <section><h2>12. Tilgængelighed, support og sikkerhed</h2><p>Vi tilstræber stabil drift og rimelig support, men lover ikke uafbrudt eller fejlfri adgang. Planlagt vedligeholdelse, sikkerhedshændelser eller forhold uden for vores kontrol kan give afbrydelser. Vi anvender rimelige tekniske og organisatoriske sikkerhedsforanstaltninger.</p></section>
        <section><h2>13. Suspension og ophør</h2><p>Vi kan suspendere adgang ved manglende betaling, væsentlig misligholdelse, sikkerhedsrisiko eller ulovlig brug. Hvor det er rimeligt, giver vi mulighed for at rette forholdet først. Ved ophør bør virksomheden eksportere nødvendige data. Sletning og opbevaring følger privatlivspolitikken og gældende lov.</p></section>
        <section><h2>14. Ansvar</h2><p>Parterne er ansvarlige efter dansk rets almindelige regler med de begrænsninger, der lovligt kan aftales mellem erhvervsdrivende. EmbedBot er ikke ansvarlig for indirekte tab, driftstab, tabt avance eller tab, der skyldes virksomhedens urigtige indhold eller brug af AI-svar uden relevant kontrol. EmbedBots samlede ansvar er, i det omfang loven tillader det, begrænset til det beløb, virksomheden har betalt for tjenesten i de seneste 12 måneder. Begrænsningen gælder ikke ved forsæt, grov uagtsomhed eller ansvar, som ikke lovligt kan begrænses.</p></section>
        <section><h2>15. Ændringer</h2><p>Væsentlige ændringer til priser eller vilkår varsles normalt mindst 30 dage før ikrafttræden. Hvis en ændring har væsentlig negativ betydning, kan virksomheden opsige abonnementet inden ændringen træder i kraft.</p></section>
        <section><h2>16. Lovvalg og kontakt</h2><p>Aftalen er underlagt dansk ret. Tvister søges først løst i dialog og kan derefter indbringes for de danske domstole efter de almindelige værnetingsregler. Spørgsmål kan sendes til <a href="mailto:axel@embedbot.dk">axel@embedbot.dk</a> eller via <Link href="/support">support</Link>.</p></section>
      </article>
    </main>
  );
}
